### ISSUE TITLE
Remove example plugins?

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin-plugins#15]
Right now if you list all Spin plugins, the following is displayed:
```sh
kagold@Kates-MacBook-Pro spin % spin plugins list
example 0.1.0
example 0.2.0
js2wasm 0.1.0
```
@karthik2804 @dicej  Should we remove both example plugins, as it is strange to have unusable examples displayed as a part of a normal user flow? Plus, now that we have an actual plugin to act as an example, the examples are not needed.

**Comment by dicej** [comment]
Yeah, that seems reasonable to me.
